# Generated by Django 6.0.5 on 2026-06-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_fr', models.CharField(blank=True, max_length=255, verbose_name='title (French)')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='slug')),
                ('venue', models.CharField(max_length=300, verbose_name='venue')),
                ('venue_fr', models.CharField(blank=True, max_length=300, verbose_name='venue (French)')),
                ('patronage', models.CharField(blank=True, help_text='Official patronage / auspices', max_length=300, verbose_name='patronage')),
                ('patronage_fr', models.CharField(blank=True, max_length=300, verbose_name='patronage (French)')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('summary', models.TextField(max_length=500, verbose_name='summary')),
                ('summary_fr', models.TextField(blank=True, max_length=500, verbose_name='summary (French)')),
                ('content', models.TextField(help_text='Full event recap in Markdown', verbose_name='content (Markdown)')),
                ('content_fr', models.TextField(blank=True, verbose_name='content (French, Markdown)')),
                ('youtube_video_id', models.CharField(blank=True, max_length=50, verbose_name='YouTube video ID')),
                ('photo_gallery', models.JSONField(blank=True, default=list, help_text='Array of image paths', verbose_name='photo gallery')),
                ('featured_image', models.ImageField(blank=True, upload_to='events/', verbose_name='featured image')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date'],
            },
        ),
    ]
