# Generated by Django 6.0.5 on 2026-05-30 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_fr', models.CharField(blank=True, max_length=255, verbose_name='title (French)')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='slug')),
                ('summary', models.TextField(max_length=500, verbose_name='summary')),
                ('summary_fr', models.TextField(blank=True, max_length=500, verbose_name='summary (French)')),
                ('content', models.TextField(verbose_name='content (Markdown)')),
                ('content_fr', models.TextField(blank=True, verbose_name='content (French, Markdown)')),
                ('skills_acquired', models.TextField(blank=True, help_text='Comma-separated list of skills', verbose_name='skills acquired')),
                ('skills_acquired_fr', models.TextField(blank=True, verbose_name='skills acquired (French)')),
                ('github_url', models.URLField(blank=True, max_length=500, verbose_name='GitHub URL')),
                ('youtube_video_id', models.CharField(blank=True, max_length=50, verbose_name='YouTube video ID')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='difficulty')),
                ('featured_image', models.ImageField(blank=True, upload_to='projects/', verbose_name='featured image')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='blog.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Project / Lab',
                'verbose_name_plural': 'Projects / Labs',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at'], name='projects_pr_publish_9215a6_idx'), models.Index(fields=['slug'], name='projects_pr_slug_7f7bd1_idx')],
            },
        ),
    ]
