# Generated by Django 6.0.5 on 2026-06-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='expert name')),
                ('headline', models.CharField(help_text='EN portfolio title', max_length=300, verbose_name='headline')),
                ('headline_fr', models.CharField(blank=True, help_text='FR portfolio title', max_length=300, verbose_name='headline (French)')),
                ('narrative', models.TextField(help_text='EN career-pivot / milestone story', verbose_name='narrative')),
                ('narrative_fr', models.TextField(blank=True, help_text='FR career-pivot / milestone story', verbose_name='narrative (French)')),
                ('youtube_video_id', models.CharField(help_text='Valid channel stream key', max_length=50, verbose_name='YouTube video ID')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='slug')),
                ('featured_image', models.ImageField(blank=True, upload_to='legends/', verbose_name='featured image')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legend',
                'verbose_name_plural': 'Legends',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
